version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods:
      - GET
      - HEAD
      - OPTIONS
      - POST
      - PUT
      - DELETE
      - PATCH
    Access-Control-Allow-Headers:
      - Authorization
      - Content-Type
      - Accept
    Access-Control-Expose-Headers:
      - Docker-Content-Digest
      - Docker-Distribution-Api-Version
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
